const filter = {
    phones: {
        'Nhu cầu sử dụng': [
            'Chơi game',
            'Pin trâu',
            'Dung lượng lớn',
            'Cấu hình cao',
            'Mỏng nhẹ',
            'Chụp ảnh đẹp',
            'Nhỏ gọn, dễ cầm nắm',
            'Livestream',
        ],
        'Loại điện thoại': ['iPhone(iOS)', 'Android', 'Điện thoại phổ thông'],
        'Bộ nhớ trong': ['128GB và 256GB', 'Trên 512GB', 'Dưới 32GB', '32GB và 64GB'],
        'Dung lượng RAM': ['Dưới 4GB', '4GB - 6GB', '8GB - 12GB', '12GB trở lên'],
        'Tính năng đặc biệt': [
            'Sạc không dây',
            'Bảo mật vân tay',
            'Nhận diện khuôn mặt',
            'Kháng nước, kháng bụi',
            'Hỗ trợ 5G',
        ],
        'Tính năng Camera': [
            'Chụp xóa phông',
            'Chụp góc rộng',
            'Quay vided 4K',
            'Chụp zoom xa',
            'Chụp macro',
            'Chống rung',
            'Quay video 8K',
        ],
        'Tần số quét': ['60Hz', '120Hz', '90Hz', 'Từ 144Hz trở lên'],
        'Kích thước màn hình': ['Dưới 6 inch', 'Trên 6 inch'],
        'Kiểu màn hình': [
            'Tai thỏ',
            'Tràn viền (không khiếm khuyết)',
            'Màn hình gập',
            'Giọt nước',
            'Đục lỗ (Nốt ruồi)',
            'Dynamic Island',
        ],
        'Chip xử lý': ['Snapdragon', 'Apple A', 'Mediatek Dimensity', 'Mediatek Helio', 'Exynos'],
    },
    laptops: {
        'Ổ cứng': ['120GB', '128GB', '256GB', '512GB', '1TB', 'HDD: 1TB', '2TB', '8TB'],
        'Dung lượng RAM': ['4GB', '8GB', '12GB', '16GB', '18GB', '24GB', '32GB', '36GB', '64GB', '128GB'],
        'CPU': [
            'Intel Core i3','Intel Core i5','Intel Core i7','Intel Core i9','Intel Celeron / Pentinum',
            'AMD Ryzen 3','AMD Ryzen 5','AMD Ryzen 7','AMD Ryzen 9',
            'Apple M1','Apple M1 Pro','Apple M1 Max','Apple M2','Apple M2 Pro','Apple M2 Max',
            'Apple M3','Apple M3 Pro','Apple M3 Max',
        ],
        'Kích thước màn hình': ['Trên 15 inch', 'Khoảng 13 inch', 'Khoảng 14 inch'],
        'Độ phân giải': ['Full HD', 'HD', '2K (Quad HD)', '4K (Ultra HD)', 'Retina', 'WQXGA', 'WUXGA', '2.8K', 'WQHD', '3.2K'],
        'Card độ họa': ['Card Onboard', 'NVIDIA GeForce Series', 'AMD Radeon Series'],
        'Tính năng đặc biệt': ['Ổ cứng SSD', 'Wi-fi 6', 'Công nghệ Intel Evo', 'Bảo mật vân tay', 'Viền màn hình siêu mỏng','Công nghệ Intel Gaming', 'Xoay gập 360 độ (2 in 1)', 'Màn hình cảm ứng', 'Nhận diện khuôn mặt', 'Thiết kế 2 trong 1'],
        'Hãng sản xuất': ['Dell', 'Lenovo', 'HP','MSI','ASUS','Acer','Gigabyte', 'LG', 'Avita', 'Huawei', 'Microsoft', 'Vaio','Xiaomi','Apple', 'Samsung'],
    },
    PCs: {
        'Kiểu màn hình': ['Màn hình phẳng', 'Màn hình cong'],
        'Tần số quét': ['60Hz','75Hz', '100Hz', '144Hz', '165Hz', '170Hz','175Hz','180Hz', '240Hz'],
        'Kích thước': ['Dưới 2 inch', '24 inch', '25 inch', '27 inch', 'Từ 28 đến 32 inch', 'Từ 34 inch trở lên', '32 inch'],
        'Độ phân giải': ['Full HD', '2K', '4K', 'WFHD','QHD', 'WQXGA', 'WUXGA', 'WQHD','UWQHD', 'DualQHD'],
        'Thời gian phản hồi': ['< 1 ms','1 ms', '2 - 3 ms', '4 - 5 ms', '6 - 10 ms'],
        'Tấm nền': ['IPS', 'WVA', 'VA', 'TN', 'LCD', 'OLED'],
        'Cổng kết nối': ['HDMI', 'Display Port', 'VGA', 'USB Type C', 'USB', 'Thunderbolt', 'DVI'],
    },
    tablets: {
        'Nhu cầu sử dụng': ['Học tập - văn phòng', 'Giải trí', 'Độ họa - sáng tạo', 'Chơi game'],
        'Tính năng đặc biệt': ['Hỗ trợ 4G/5G - Có nghe gọi', 'Hỗ trợ bút cảm ứng', 'Cảm biến vân tay', 'Nhận diện khuôn mặt', 'Pin khủng', 'Sạc nhanh', 'Màn hình lớn', 'Hỗ trợ bàn phím'],
        'Bộ nhớ trong': ['Dưới 32GB', '32GB và 64GB', '128GB và 256GB', 'Trên 512GB', '1TB', '2TB'],
        'Kích thước màn hình': ['Khoảng 7 - 8 inch', 'Từ 10 - 11 inch', 'Từ 12 inch trở lên'],
        'Hệ điều hành': ['iPadOS', 'Android', 'HarmonyOS'],
        'Chipset': ['Snapdragon 8 Gen 2 for Galaxy','Snapdragon', 'Apple A-series', 'Apple M1','Apple M2',],
    },
    audio: {
        'Tai nghe': ['Bluetooth', 'Có dây', 'Chụp tai', 'Gaming', 'Thể thao'],
        'Loa': ['Bluetooth', 'Soundbar', 'Karaoke', 'Loa vi tính'],
        'Micro': ['Thu âm', 'Karaoke', 'Cáp âm thanh'],
    },
    smartWatchs: {
        'Kích cỡ mặt đồng hồ': ['Cho nữ (<41mm)', 'Cho nam (42-47mm)', 'Từ 45mm trở lên'],
        'Chất liệu viền': ['Nhôm', 'Thép', 'Nhựa', 'Polymer', 'Titanium'],
        'Tính năng thông minh': ['Có định vị GPS', 'Phát nhạc trên đồng hồ', 'Nghe gọi trên đồng hồ',
            'Màn hình luôn hiển thị', 'Nâng cổ tay sáng màn hình', 'Điều khiển chụp ảnh', 'Kết nối tai nghe', 
            'Xem bản đồ', 'Nhận thông báo cuộc gọi', 'Sạc năng lượng mặt trời', 'Nghe gọi qua Bluetooth', 'Nghe gọi qua eSim'
        ],
        'Thiết kế': ['Mặt tròn', 'Mặt vuông', 'Chuẩn quân đội', 'Mặt chữ nhật'],
        'Tiện ích sức khỏe': ['Chế độ luyện tập', 'Đo nhịp tim', 'Đo lượng oxy trong máu', 'Tính quãng đường chạy',
            'Đo huyết áp', 'Phát hiện té ngã', 'Thay đổi chu kỳ', 'Đo đường huyết'
        ],
        'Môn thể thao': ['Leo núi, thám hiểm', 'Đạp xe', 'Chạy bộ', 'Bơi lội', 'Lặn chuyên nghiệp'],
        'Chuẩn kháng nước': ['10ATM', '5ATM'],
    },
};

export default filter;
